
# Auto-generated by Interface Designer
#
# WARNING: Any manual changes made to this file will be lost when generating constraints.

# Efinity Interface Designer SDC
# Version: 2026.1.132
# Date: 2026-08-25 22:42

# Copyright (C) 2013 - 2026 Efinix Inc. All rights reserved.

# Device: Ti60F225
# Project: conv10_10
# Timing Model: I3 (final)

# PLL Constraints
###################
create_clock -period 10.417 -name pll_inst1_CLKOUT0 [get_ports {pll_inst1_CLKOUT0}]
create_clock -period 5.208 -name pll_inst1_CLKOUT1 [get_ports {pll_inst1_CLKOUT1}]
create_clock -period 108.507 -name pll_inst1_CLKOUT2 [get_ports {pll_inst1_CLKOUT2}]

# GPIO Constraints
####################
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -max <MAX CALCULATION> [get_ports {led}]
# set_output_delay -clock <CLOCK> [-reference_pin <clkout_pad>] -min <MIN CALCULATION> [get_ports {led}]

# Clock Latency Constraints
############################
# set_clock_latency -source -setup <board_max + 2.193> [get_ports {pll_inst1_CLKOUT0}]
# set_clock_latency -source -hold <board_min + 1.271> [get_ports {pll_inst1_CLKOUT0}]
# set_clock_latency -source -setup <board_max + 2.193> [get_ports {pll_inst1_CLKOUT1}]
# set_clock_latency -source -hold <board_min + 1.271> [get_ports {pll_inst1_CLKOUT1}]
# set_clock_latency -source -setup <board_max + 2.193> [get_ports {pll_inst1_CLKOUT2}]
# set_clock_latency -source -hold <board_min + 1.271> [get_ports {pll_inst1_CLKOUT2}]
